export const candidateLabels = [
  "Agriculture and Farming",
  "Artificial Intelligence",
  "Arts and Entertainment",
  "Business and Finance",
  "Career and Jobs",
  "Economics and Trade",
  "Education and Learning",
  "Environment and Ecology",
  "Fashion and Beauty",
  "Fitness and Wellness",
  "Food and Drink",
  "Games",
  "Health and Medicine",
  "History and Culture",
  "Law and Crime",
  "Literature and Books",
  "Marketing and Advertising",
  "Media and Journalism",
  "Military and Defense",
  "Movies and TV",
  "Music",
  "News and Current Events",
  "Parenting and Family",
  "Personal Development",
  "Pets and Animals",
  "Philosophy and Ethics",
  "Photography",
  "Politics and Government",
  "Relationships and Dating",
  "Religion and Spirituality",
  "Robotics",
  "Safety and Security",
  "Shopping",
  "Space and Astronomy",
  "Sports",
  "Technology and Science",
  "Transportation and Automotive",
  "Travel and Lifestyle",
];

export const colors = [
  'magenta', 'red', 'volcano', 'orange', 'gold', 
  'lime', 'green', 'cyan', 'blue', 'geekblue', 'purple'
];

export const maxResults = 50;
